Action Test sed

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -12,21 +12,21 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Check commit status
-      id: commit-status
-      run: |
-        # Check the status of the Git commit
-        CURRENT_STATUS=$(curl --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r '.state');
-        echo "Current status is: $CURRENT_STATUS"
-        while [ "${CURRENT_STATUS^^}" = "PENDING" ];
-          do sleep 20;
-          CURRENT_STATUS=$(curl --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r '.state');
-        done;
-        echo "Current status is: $CURRENT_STATUS"
-        if [ "${CURRENT_STATUS^^}" = "FAILURE" ];
-          then echo "Commit status failed. Canceling execution";
-          exit 1;
-        fi
+    # - name: Check commit status
+    #   id: commit-status
+    #   run: |
+    #     # Check the status of the Git commit
+    #     CURRENT_STATUS=$(curl --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r '.state');
+    #     echo "Current status is: $CURRENT_STATUS"
+    #     while [ "${CURRENT_STATUS^^}" = "PENDING" ];
+    #       do sleep 20;
+    #       CURRENT_STATUS=$(curl --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r '.state');
+    #     done;
+    #     echo "Current status is: $CURRENT_STATUS"
+    #     if [ "${CURRENT_STATUS^^}" = "FAILURE" ];
+    #       then echo "Commit status failed. Canceling execution";
+    #       exit 1;
+    #     fi
 
 
     - name: Checkout
@@ -40,6 +40,7 @@ jobs:
           # echo ${{ secrets.AWS_EXECUTION_ROLE_ARN }}
           # export AWS_EXECUTION_ROLE_ARN=${{ secrets.AWS_EXECUTION_ROLE_ARN }}
           # echo $AWS_EXECUTION_ROLE_ARN
+          ls -ltr .
           sed "s|aws_execution_role_arn|${AWS_EXECUTION_ROLE_ARN}|" task-definition.json.template > task-definition.json
           cat task-definition.json
 
